version: '3.7'

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: Tweetbook/
    restart: always
    ports:
      - "7000:80"
    depends_on:
      - db-server
    networks:
      - localdev

  db-server:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Misky1234
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    networks:
      - localdev